twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_env: '%env(APP_ENV)%'
        google_tracking_id: '%env(GOOGLE_TRACKING_ID)%'